### ISSUE TITLE
Invalid snak data

### ISSUE THREAD

**Issue by kodymoodley** [HeardLibrary/digital-scholarship#3]
Running the [write-statements](https://github.com/HeardLibrary/digital-scholarship/blob/master/code/wikibase/api/write-statements.py) script on a local wikibase instance results in the following error: 

`Write confirmation:  {'error': {'code': 'invalid-snak', 'info': 'Invalid snak data.', 'messages': [{'name': 'wikibase-api-invalid-snak', 'parameters': [], 'html': {'*': 'Invalid snak data.'}}], '*': 'See http://.../w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.'}}`. 

I have updated Lines 129 - 131 in the script to refer to items that have been verified to exist in my local Wikibase instance.

I suspect the error is related to the issue of how to represent the JSON "value" property that is an item and not a string as discussed in the "Time for a snak" section of this blog post: http://baskauf.blogspot.com/2019/06/putting-data-into-wikidata-using.html.

However, the [Wikibase API sandbox](https://www.wikidata.org/wiki/Special:ApiSandbox#action=wbcreateclaim&entity=Q4115189&property=P9003&snaktype=value&value=%7B%22entity-type%22:%22item%22,%22numeric-id%22:1%7D) also gives the same error when providing a seemingly valid `value` property e.g. `{"entity-type":"item","numeric-id":1}` for the `wbcreateclaim` endpoint. Interestingly, the sandbox does respond successfully when providing the following value: `"{\"entity-type\":\"item\",\"numeric-id\":1}"` however, use of quotes in this manner appears to treat the value as a string and not an item, the latter is the expected behavior.

My goal is conceptually simple - I just want to be able to add a triple (e.g. `Q6 P4 Q9`) to a Wikibase instance using Python. Your [write-statements](https://github.com/HeardLibrary/digital-scholarship/blob/master/code/wikibase/api/write-statements.py) script appears to be the closest or most relevant potential solution. I have tried [https://github.com/SuLab/WikidataIntegrator](https://github.com/SuLab/WikidataIntegrator) and [https://github.com/samuelmeuli/wikibase-api](https://github.com/samuelmeuli/wikibase-api), both unsuccessfully.

**Comment by baskaufs** [comment]
Hi @kodymoodley The code you are working with is several years old and since that time I've been working quite a bit on more sophisticated code to write to Wikidata or any other Wikibase instance. The result is the VanderBot API writing script, described [here](https://github.com/HeardLibrary/linked-data/blob/master/vanderbot/README.md). It is specifically designed to take CSV data as input, but if you want to look at the code, you can find parts that might help you drill down to more specifics about encoding the data before sending it to the API. 

The overall strategy I ended up using was to construct the snaks as complex Python data objects (lists and dictionaries). You can see examples for various kinds of values starting [here](https://github.com/HeardLibrary/linked-data/blob/master/vanderbot/vanderbot.py#L1580). Once I constructed all of the snaks that I wanted to write to the API, in [line 1727](https://github.com/HeardLibrary/linked-data/blob/master/vanderbot/vanderbot.py#L1726) I then used the `json.dumps()` function to convert the Python data structure into valid JSON. This was the easiest way to avoid problems with trying to do the escaping/encoding required to generate the JSON that you were having problems with. 

The actual write to the API is initiated in line 1739, which calls the `attemptPost()` function [here](https://github.com/HeardLibrary/linked-data/blob/master/vanderbot/vanderbot.py#L958). If you are writing to your own Wikibase instance, this function is more complicated than you need but for writing to Wikidata itself, it's necessary to respect the Maxlag returned when the server is busy with a lot of other users. It took some work to figure that out, but the function works pretty well by increasing the wait time with each try and then trying for up to 5 minutes until it's successful. In most cases, that's long enough. If you are the only user of your Wikibase, then you don't need to worry about this. 

The code also throttles the rate of writing to the API to 50 writes per minute in [line 221](https://github.com/HeardLibrary/linked-data/blob/master/vanderbot/vanderbot.py#L215). At Wikidata, you'll get blocked if you write more often than that without a bot flag. For your own Wikibase instance, you can set the delay in line 221 to zero. 

You should be able to use this script (or parts hacked from it) with any Wikibase instance by setting the `endpointUrl` to the URL of the Wikibase (including a localhost URL). The format of the credentials file is in line 122 and is also described in the [script details](https://github.com/HeardLibrary/linked-data/blob/master/vanderbot/README.md#script-details) on the landing page. The login process follows the blog post you read and the various steps are carried out in the functions starting in [line 251](https://github.com/HeardLibrary/linked-data/blob/master/vanderbot/vanderbot.py#L251).

I hope that you can get something useful out of the code. It gets complicated in the parts that involve parsing out the data from the CSV file and then in extracting data from the API response, but the part of the code that does what you are trying to do is relatively simple and hopefully has enough comments that it will make sense to you.

Good luck!
Steve

**Comment by kodymoodley** [comment]
Hi @baskaufs Thank you so much for the detailed information! I suspect VanderBot would be very useful for me in the near future for the kind of importing I need to do. I come from the Semantic Web / RDF world and, to my detriment, presumed that Wikibase / Wikidata would support mass import of RDF data (seeing as how Wikidata espouses the Linked Data paradigm). So I set up an elaborate pipeline to convert data from a MySQL database into RDF and then when it got down to importing to Wikibase I realised that there is a completely different data model (the snaks thing)! Seeing as though my original data is in an SQL database, exporting to CSV is a much simpler process and hopefully I could then use VanderBot for the import - rather than building a script to import triples from an RDF graph. The snaks data model took some time for me to understand. I also found that Wikibase API implementation creates properties with string data types as the default, and furthermore the typing is strict and fixed. I.e., if you create a property P4 with "string" datatype then you can never use this property to add a statement like Q3 P4 Q5 because Q5 is a "wikibase-item" type and not a string. This makes sense but it is not made clear in the documentation, and the error messages from the API are not very specific or informative.

**Comment by baskaufs** [comment]
@kodymoodley I can understand your frustration if you generated the RDF graph and then found you couldn't use it!

Since I've been mostly writing to Wikidata, I haven't had to create properties very often, and in generic Wikibase I've only created them manually. But my investigation of the snak formats has made me aware of all of the value types described in the Wikibase model. Each one has some kind of mapping to RDF (plain literal, language-tagged literal, IRI value, or complex node type) so it's a bit of a challenge to connect those with the snak JSON format. 

I also agree that the API documentation leaves a lot to be desired. A lot of times, I'd just have to figure things out by trial and error when there weren't enough examples in the documentation. One useful think I discovered was that the API's response included snak JSON that was basically in the same form as the JSON you needed to write to the API. So I could do some kind of API interaction with an item that had statement value types I wanted to know about, and then try to mimic the JSON I got back.  

I haven't actually tried to create any properties using the API, but my guess is that you might get a similar response that might help you structure the JSON to send to the API to create the property. 

Good luck and let me know how things work out for you.
